(module unicalc-db racket

;; Define database db for Unicalc
;; by Robert Keller
;;
;; Version 2019 October 29

;; The Unicalc database is an association list of pairs.
;; Each pair consists of a unit and a list defining the unit.
;; Units are atoms.
;; Quantities are represented as 3-element lists: numeric multiplier, numerator, denominator
;; Both numerator and denominator are lists of units.
;; It is assumed that they do not have any units in common and are sorted

(define unicalc-db '(
(A                      (1 (ampere)()))
(AU                     (1 (astronomical_unit)()))
(C                      (1 (coulomb)()))
(Dirac_constant         (1.054571628e-34 (joule second)()))
(F                      (1 (farad)()))
(G                      (1 (gravitational_constant)()))
(H                      (1 (henry)()))
(Hz                     (1 (hertz)()))
(J                      (1 (joule)()))
(N                      (1 (newton)()))
(Planck_constant        (6.62606896e-34 (joule second)()))
(S                      (1 (siemens)()))
(T                      (1 (tesla)()))
(V                      (1 (volt)()))
(W                      (1 (watt)()))
(Wb                     (1 (weber)()))
(acre                   (43560 (foot foot)()))
(amp                    (1 (ampere)()))
(amu                    (1 (atomic_mass_unit)()))
(angstrom               (1/10000000000 (meter)()))
(apoth_dram             (60 (grain)()))
(apoth_ounce            (480 (grain)()))
(apoth_pound            (5760 (grain)()))
(are                    (100 (meter meter)()))
(astronomical_unit      (149600000000 (meter)()))
(atmosphere             (101325 (pascal)()))
(atomic_mass_unit       (1 (dalton)()))
(bar                    (100000 (pascal)()))
(barn                   (1e-28 (meter meter)()))
(barrel                 (31.5 (gallon)()))
(baryl                  (1 (dyne) (centimeter centimeter)))
(baud                   (1 (bit)(second)))
(bbl                    (1 (barrel)()))
(bolt                   (40 (yard)()))
(british_gallon         (1.20095 (gallon)()))
(btu                    (1055.06 (joule)()))
(bucket                 (18180 (centimeter centimeter centimeter)()))
(bushel                 (4 (peck)()))
(byte                   (8 (bit)()))
(c                      (1 (speed_of_light)()))
(cable                  (720 (foot)()))
(cal                    (1 (calorie)()))
(caliber                (1/1000 (inch)()))
(calorie                (4.1868 (joule)()))
(candle                 (1 (candela)()))
(carat                  (200 (milligram)()))
(cd                     (1 (candela)()))
(centare                (1/100 (are)()))
(centimeter             (1/100 (meter)()))
(century                (10 (decade)()))
(chain                  (66 (foot)()))
(chronon                (1e-24 (second)()))
(cm                     (1 (centimeter)()))
(coulomb                (1 (ampere second)()))
(cup                    (1/2 (pint)()))
(curie                  (3.7037e10 (becquerel)()))
(dalton                 (1.6605654e-24 (gram)()))
(daraf                  (1 ()(farad)))
(day                    (24 (hour)()))
(decade                 (10 (year)()))
(degree                 (1 (radian)(pi)))
(dozen                  (12 ()()))
(dram                   (1/256 (pound)()))
(dry_barrel             (105 (dry_quart)()))
(dry_pint               (1/2 (dry_quart) ()))
(dry_quart              (67.2 (inch inch inch)()))
(dyne                   (0.00001 (newton)()))
(electron_volt          (1.60218925e-20 (joule)()))
(ell                    (45 (inch)()))
(em                     (0.167 (inch)()))
(en                     (1/2 (em)()))
(erg                    (1/1000000 (joule)()))
(ev                     (1 (electron_volt)()))
(farad                  (1 (coulomb) (volt)))
(faraday                (96490 (coulomb)()))
(fathom                 (6 (foot)()))
(feet                   (1 (foot)()))
(fermi                  (1e-15 (meter) ()))
(firkin                 (90 (pound)()))
(fl_oz                  (1 (fluid_ounce)()))
(fluid_dram             (1/8 (fluid_ounce) ()))
(fluid_ounce            (1/8 (cup)()))
(flux_unit              (1e-26 (watt) (Hz meter meter)))
(foot                   (12 (inch)()))
(fortnight              (2 (week) ()))
(free_acceleration      (9.80665 (meter) (second second)))
(ft                     (1 (foot)()))
(furlong                (40 (rod)()))
(g                      (1 (gram)()))
(gallon                 (231 (inch inch inch)()))
(gauss                  (1/10000 (tesla)()))
(gev                    (1000000000 (ev)()))
(gilbert                (1 (ampere turn)()))
(gill                   (1/4 (pint)()))
(grain                  (1/7000 (pound)()))
(gram                   (1/1000 (kg)()))
(grav                   (1 (free_acceleration)()))
(gravitational_constant (6.67259e-11 (meter meter newton) (kg kg)))
(gross                  (12 (dozen)()))
(h                      (1 (Planck_constant)()))
(hand                   (4 (inch)()))
(hectare                (100 (are)()))
(henry                  (1 (weber) (ampere)))
(hertz                  (1 ()(second)))
(hogshead               (63 (gallon)()))
(horsepower             (550 (foot pound_force) (second)))
(hour                   (60 (minute)()))
(hp                     (1 (horsepower)()))
(hr                     (1 (hour)()))
(in                     (1 (inch)()))
(inch                   (0.0254 (meter)()))
(inches                 (1 (inch)()))
(joule                  (1 (kg meter meter) (second second)))
(kilogram               (1 (kg)()))
(kilogram_force         (1 (kg free_acceleration)()))
(kilometer              (1000 (meter)()))
(km                     (1 (kilometer)()))
(knot                   (1 (nautical_mile) (hour)))
(kph                    (1 (kilometer)(hour)))
(kwh                    (1 (kilowatt hour)()))
(l                      (1 (liter)()))
(lambert                (3.142 (candela) (centimeter centimeter)))
(lb                     (1 (pound)()))
(league                 (3 (mile)()))
(light_year             (9460730472580800 (meter)()))
(link                   (1/100 (chain) ()))
(liter                  (1000 (centimeter centimeter centimeter)()))
(litre                  (1 (liter)()))
(lm                     (1 (lumen)()))
(long_ton               (2240 (pound) ()))
(lumen                  (1 (candela steradian) ()))
(lux                    (1 (lumen) (meter meter)))
(lx                     (1 (lux)()))
(m                      (1 (meter)()))
(maxwell                (0.00000001 (weber)()))
(megohm                 (1000000 (ohm)()))
(metre                  (1 (meter)()))
(metric_ton             (1000 (kg)()))
(mev                    (1000000 (electron_volt)()))
(mho                    (1 (siemens)()))
(microhm                (1/1000000 (ohm)()))
(micron                 (1/1000000 (meter)()))
(microsecond            (1/1000000 (second)()))
(mil                    (1/1000 (inch)()))
(mile                   (8 (furlong)()))
(millenium              (10 (century)()))
(millimeter             (1/1000 (meter)()))
(millisecond            (1/1000 (second)()))
(min                    (1 (minute)()))
(minute                 (60 (second)()))
(mm                     (1 (millimeter)()))
(mol                    (1 (mole)()))
(mole                   (6.02253e23 ()()))
(mph                    (1 (mile)(hour)))
(ms                     (1 (millisecond)()))
(nautical_mile          (1.15078 (mile)()))
(newton                 (1 (joule) (meter)))
(nibble                 (4 (bit)()))
(ohm                    (1 (volt)(ampere)))
(oil_barrel             (42 (gallon)()))
(ounce                  (1/16 (pound)()))
(parsec                 (30856770000000000 (meter)()))
(pascal                 (1 (newton) (meter meter)))
(pc                     (1 (parsec)()))
(peck                   (8 (dry_quart)()))
(pennyweight            (24 (grain)()))
(pi                     (3.14159265358979323846 ()()))
(pica                   (12 (point)()))
(pint                   (1/2 (quart)()))
(point                  (0.013837 (inch)()))
(poise                  (1/10 (pascal) (second)))
(pound                  (0.45359237 (kg) ()))
(pound_force            (1 (free_acceleration pound) ()))
(poundal                (1 (foot pound)(second second)))
(psi                    (1 (pound_force)(inch inch)))
(pt                     (1 (pint)()))
(qt                     (1 (quart)()))
(quadrant               (90 (degree)()))
(quart                  (1/4 (gallon)()))
(revolution             (4 (quadrant)()))
(reyn                   (68947.6 (poise)()))
(rod                    (33/2 (foot)()))
(rood                   (1/4 (acre)()))
(rope                   (20 (foot)()))
(rpm                    (1 (revolution)(second)))
(s                      (1 (second)()))
(scruple                (20 (grain)()))
(sec                    (1 (second)()))
(section                (1 (mile mile)()))
(siemens                (1 (ampere) (volt)))
(skein                  (360 (foot)()))
(slug                   (32.1740 (pound)()))
(span                   (9 (inch)()))
(speed_of_light         (299792458 (meter) (second)))
(stadion                (622 (foot)()))
(stadium                (202 (yard)()))
(stokes                 (0.0001 (meter meter) (second)))
(survey_mile            (320 (rod)()))
(tablespoon             (1/2 (fluid_ounce)()))
(tbsp                   (1 (tablespoon)()))
(teaspoon               (1/3 (tablespoon)()))
(tesla                  (1 (weber) (meter meter)))
(therm                  (1e5 (btu)()))
(ton                    (2000 (pound)()))
(torr                   (0.001315789473684210526 (atmosphere)()))
(township               (36 (section)()))
(troy_ounce             (20 (pennyweight)()))
(troy_pound             (12 (troy_ounce)()))
(tsp                    (1 (teaspoon)()))
(us                     (1 (microsecond)()))
(volt                   (1 (joule) (coulomb)))
(watt                   (1 (joule) (second)))
(weber                  (1 (volt second)()))
(week                   (7 (day) ()))
(yard                   (0.9144 (meter)()))
(yd                     (1 (yard)()))
(year                   (365 (day)()))
(yr                     (1 (year)()))
))
  
  
(provide unicalc-db)
)

